Repository puppetlabs/puppetlabs-powershell, pull requests merged in 2020-01, with the labels that each got.

#275 (MODULES-10373) - Support added for Changelog Generator
  .sync.yml
  .travis.yml
  Gemfile
  HISTORY.md
  metadata.json
Labels: maintenance

#276 (MODULES-10373) - 3.0.0 Release Merge-back
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance

#277 (MODULES-10389) - Safeguard powershell provider loading
  lib/puppet/provider/exec/powershell.rb
  lib/puppet/provider/exec/pwsh.rb
Labels: bug

#278 (MAINT) - update dependencies
  metadata.json
Labels: maintenance

#280 (maint) disable forge upload
  .sync.yml
  .travis.yml
  Gemfile
  metadata.json
Labels: maintenance

#281 (MODULES-10164) Release version v3.0.1
  CHANGELOG.md
  metadata.json
Labels: maintenance

#274 pdksync - (maint) travis updates: bundler and slack
  .sync.yml
  .travis.yml
  metadata.json
Labels: maintenance

#282 Correct supported Puppet lower bound to 5.5.0
  metadata.json
Labels: backwards-incompatible
