Repository puppetlabs/puppetlabs-powershell, pull requests merged in 2022-03, with the labels that each got.

#370 pdksync - (FM-8922) - Add Support for Windows 2022
  metadata.json
Labels: feature

#372 pdksync - (GH-iac-334) Remove Support for Ubuntu 14.04/16.04
  metadata.json
Labels: bugfix

#373 pdksync - Add labeller and stale GHA workflows
  .github/workflows/labeller.yml
  .github/workflows/stale.yml
Labels: maintenance
