Repository puppetlabs/puppetlabs-powershell, pull requests merged in 2022-10, with the labels that each got.

#384 pdksync - (CONT-130) - Dropping Support for Debian 9
  metadata.json
Labels: bugfix, hacktoberfest

#386 pdksync - (PDKSync) Removal of puppet_module_gems
  .devcontainer/README.md
  Gemfile
  metadata.json
Labels: maintenance, hacktoberfest

#389 (CONT-133) Update outdated spec tests
  spec/unit/provider/exec/powershell_spec.rb
  spec/unit/provider/exec/pwsh_spec.rb
Labels: maintenance
